### ISSUE TITLE
Create SHE Game Night Banner

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/community#23]
Create SHE Game Night Banner in English and Spanish.

Perhaps include some text like "SHE plays with everyone".

Use your best judgement on the translation from English to Spanish.

Goal for completion Tuesday May 18th.

Try to spend maximum 1.5-2hrs.

**Comment by chair28980** [comment]
Assigning to Rohekbenitez

**Comment by chair28980** [comment]
I'll leave this assigned to me as I work on Github Permissions in sync with Zenhub. Rohek is working on this currently.

**Comment by Rohekbenitez** [comment]
great!

**Comment by chair28980** [comment]
@Rohekbenitez  Great start, need to edit the image file to be one single image and the file to be a .png file and we'll be all set.

**Comment by chair28980** [comment]
@Rohekbenitez Awesome stuff!

[Uploading... GameNight.png]
