### ISSUE TITLE
Create DAO Rush Week Event Anouncement

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/community#4]
- Date of Event
- Will happen on ZOOM call
- People will Livestream their Challenge which will be saved and posted to youtube
- Users can post that in DIDATHING to earn CRED

- We need to make a FORM where people can sign up to do challenges
- First come first served
- Limit 2 minute per challenge
- Example: 50 pushups, 5 pullups, kickflip, etc

https://www.figma.com/file/ryVztKPz1I2DU7EGzqKPKm/SHE-Flyer-for-DAO-Rush-Week?node-id=1%3A4

**Comment by youngkidwarrior** [comment]
update: we can use a discord stage for this
Here is the google form: https://docs.google.com/forms/d/1IjBfJSWxPldeOen0IrETLPGcT_LqFY3csqeFwQIqfEM/viewform?edit_requested=true

**Comment by kittyslasher** [comment]
@youngkidwarrior @chair28980 Are we wanting an announcement post for discord or for twitter? Where is the announcement post going?

**Comment by kittyslasher** [comment]
Completed with the creation of this tweet
https://discord.com/channels/@me/836460306438946836/836511316646690839
